AllCops:
  Exclude:
    - Guardfile
    - vendor/**/*
    - example.rb
Metrics/AbcSize:
  Enabled: false
Style/LineLength:
  Enabled: false
Style/MethodLength:
  Enabled: false
#Style/SpecialGlobalVars:
#  Enabled: false
